import { User } from "src/interfaces/user";

const getRandomImage = (): string => {
  const randomSize = Math.floor(Math.random() * 300) + 1;
  return `https://i.pravatar.cc/${randomSize}`;
};

const dummyAddress = {
  street: "123 Main St",
  city: "Stockholm",
  state: "ST",
  postalCode: "12345",
  country: "Sweden",
};

export const MockedUser: User = {
  userId: 1,
  email: "john.doe1@example.com",
  firstName: "John",
  lastName: "Doe",
  phoneNumber: "1234567890",
  countryCode: "US",
  desc: "First user in the list",
  img: getRandomImage(),
  gender: "male",
  birthday: { year: 1990, month: 5, day: 15 },
  height: 180,
  hashedPassword: "hashed_password_1",
  address: dummyAddress,
};

export const users: User[] = [
  {
    userId: 0,
    email: "zldwkd93.business@gmail.com",
    firstName: "Jimmy",
    lastName: "Hwang",
    phoneNumber: "0724462942",
    countryCode: "46",
    desc: "Founder",
    img: "https://media.licdn.com/dms/image/D4D03AQGIxd-BionXWQ/profile-displayphoto-shrink_800_800/0/1683486219744?e=1701302400&v=beta&t=iibgoRdGza1rALmAZhHlOm4SCme1chE4xsTtYnLT79g",
    gender: "male",
    birthday: { year: 1993, month: 8, day: 11 },
    height: 182,
    hashedPassword: "hashed_password_1",
    address: dummyAddress,
    role: "Engineer",
  },
  {
    userId: 1,
    email: "jane.doe2@example.com",
    firstName: "Jane",
    lastName: "Doe",
    phoneNumber: "1234567891",
    countryCode: "46",
    desc: "Second user in the list",
    img: getRandomImage(),
    gender: "female",
    birthday: { year: 1992, month: 3, day: 10 },
    height: 165,
    hashedPassword: "hashed_password_2",
    address: dummyAddress,
  },
  {
    userId: 2,
    email: "amy.wong3@example.com",
    firstName: "Amy",
    lastName: "Wong",
    phoneNumber: "1234567892",
    countryCode: "UK",
    desc: "Third user in the list",
    img: getRandomImage(),
    gender: "female",
    birthday: { year: 1995, month: 4, day: 20 },
    height: 170,
    hashedPassword: "hashed_password_3",
    address: dummyAddress,
  },
  {
    userId: 3,
    email: "robert.frost4@example.com",
    firstName: "Robert",
    lastName: "Frost",
    phoneNumber: "1234567893",
    countryCode: "AU",
    desc: "Fourth user in the list",
    img: getRandomImage(),
    gender: "male",
    birthday: { year: 1985, month: 7, day: 30 },
    height: 185,
    hashedPassword: "hashed_password_4",
    address: dummyAddress,
  },
  {
    userId: 4,
    email: "sarah.smith5@example.com",
    firstName: "Sarah",
    lastName: "Smith",
    phoneNumber: "1234567894",
    countryCode: "NZ",
    desc: "Fifth user in the list",
    img: getRandomImage(),
    gender: "female",
    birthday: { year: 1988, month: 6, day: 5 },
    height: 175,
    hashedPassword: "hashed_password_5",
    address: dummyAddress,
  },
  {
    userId: 5,
    email: "michael.jones6@example.com",
    firstName: "Michael",
    lastName: "Jones",
    phoneNumber: "1234567895",
    countryCode: "UK",
    desc: "Sixth user in the list",
    img: getRandomImage(),
    gender: "male",
    birthday: { year: 1993, month: 8, day: 23 },
    height: 182,
    hashedPassword: "hashed_password_6",
    address: dummyAddress,
  },
  {
    userId: 6,
    email: "linda.brown7@example.com",
    firstName: "Linda",
    lastName: "Brown",
    phoneNumber: "1234567896",
    countryCode: "US",
    desc: "Seventh user in the list",
    img: getRandomImage(),
    gender: "female",
    birthday: { year: 1985, month: 9, day: 30 },
    height: 168,
    hashedPassword: "hashed_password_7",
    address: dummyAddress,
  },
  {
    userId: 7,
    email: "james.wilson8@example.com",
    firstName: "James",
    lastName: "Wilson",
    phoneNumber: "1234567897",
    countryCode: "CA",
    desc: "Eighth user in the list",
    img: getRandomImage(),
    gender: "male",
    birthday: { year: 1989, month: 11, day: 11 },
    height: 173,
    hashedPassword: "hashed_password_8",
    address: dummyAddress,
  },
  {
    userId: 8,
    email: "patricia.johnson9@example.com",
    firstName: "Patricia",
    lastName: "Johnson",
    phoneNumber: "1234567898",
    countryCode: "AU",
    desc: "Ninth user in the list",
    img: getRandomImage(),
    gender: "female",
    birthday: { year: 1991, month: 12, day: 15 },
    height: 160,
    hashedPassword: "hashed_password_9",
    address: dummyAddress,
  },
  {
    userId: 9,
    email: "john.doe1@example.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "1234567890",
    countryCode: "US",
    desc: "First user in the list",
    img: getRandomImage(),
    gender: "male",
    birthday: { year: 1990, month: 5, day: 15 },
    height: 180,
    hashedPassword: "hashed_password_1",
    address: dummyAddress,
  },
];

export const mockedUserData = {
  status: "success",
  message: "User logged in successfully",
  result: {
    token: "mocked-token-value",
    user: {
      _id: "6512c66fdbdbd632d31fbc95",
      name: "jimmy",
      email: "test71@email.com",
      bookings: [],
      events: [],
      favoriteIds: [],
      hashedPassword: "mocked-hash-value",
      isEmailVerified: false,
      listings: [],
      messages: [],
      notifications: [],
      pastEventsAttended: [],
      reviews: [],
      savedEvents: [],
      __v: 0,
    },
  },
};
