export const jobList = [
  {
    title: "Business Development Manager",
    location: "STOCKHOLM, SWEDEN",
    category: "BUSINESS DEVELOPMENT",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Sales Executive",
    location: "STOCKHOLM, SWEDEN",
    category: "BUSINESS DEVELOPMENT",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Partnership Coordinator",
    location: "STOCKHOLM, SWEDEN",
    category: "BUSINESS DEVELOPMENT",
    type: "PART-TIME",
    contract: "HYBRID",
  },
  {
    title: "Lead Generation Specialist",
    location: "STOCKHOLM, SWEDEN",
    category: "BUSINESS DEVELOPMENT",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Account Manager",
    location: "STOCKHOLM, SWEDEN",
    category: "BUSINESS DEVELOPMENT",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Sales Operations Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "BUSINESS DEVELOPMENT",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Software Engineer",
    location: "STOCKHOLM, SWEDEN",
    category: "IT",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Backend Developer",
    location: "STOCKHOLM, SWEDEN",
    category: "IT",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Frontend Developer",
    location: "STOCKHOLM, SWEDEN",
    category: "IT",
    type: "PART-TIME",
    contract: "HYBRID",
  },
  {
    title: "System Administrator",
    location: "STOCKHOLM, SWEDEN",
    category: "IT",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Network Engineer",
    location: "STOCKHOLM, SWEDEN",
    category: "IT",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Security Specialist",
    location: "STOCKHOLM, SWEDEN",
    category: "IT",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Accountant",
    location: "BERLIN, GERMANY",
    category: "ACCOUNTING",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Technical Accounting Specialist",
    location: "STOCKHOLM, SWEDEN",
    category: "ACCOUNTING",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Technical Accounting Specialist",
    location: "STOCKHOLM, SWEDEN",
    category: "ACCOUNTING",
    type: "HYBRID",
    contract: "",
  },
  {
    title: "2nd Line Operational Risk Manager: Third Party",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "AML Data Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Business Data Analyst - Credit",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Credit Risk Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Financial Controller",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Financial Controller",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Financial Risk Manager",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Recoveries Senior Manager",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "GOTO UK Collections & Recoveries Senior Manager",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Product Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Product Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Risk Manager",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst - Partner Success Team",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Analyst - Partner Success Team",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Cash Manager - Treasury",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Cash Manager - Treasury",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Credit Risk Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "ON-SITE",
  },
  {
    title: "Senior Data Analyst - Customer Service",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Product Analyst",
    location: "STOCKHOLM, SWEDEN",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
  {
    title: "Senior Product Analyst",
    location: "BERLIN, GERMANY",
    category: "ANALYTICS",
    type: "FULL-TIME",
    contract: "HYBRID",
  },
];
